from shared.catalyst_client import ztsql_query

# BUG FIX: previously queried `cases JOIN units ON c.unit_id = u.unit_id` to
# resolve district -- but no `unit_id`/`units` data was ever generated by
# data/scripts/generate_base_firs.py (FIRs only carry district_name, used for
# the graph ingestion, not the relational one), and the actual seeding
# scripts (data/scripts/ingest_all.py, plant_trap_scenario.py) insert into
# `cases` with only (fir_internal_id, crime_no, registered_date, crime_head_id,
# crime_sub_head_id) -- no district column at all. Filtering by district here
# was unimplementable with the data that actually exists. Filters by resolved
# crime_sub_head_id instead, which the data does support and which
# entity_lookup_resolver.py already resolves from free-text crime-type mentions.

async def search_cases_by_crime_sub_head(crime_sub_head_id: str, limit: int = 50) -> list:
    """
    Structured filtering of cases by resolved crime sub-head classification
    (e.g. "murder", "robbery" -> its crime_sub_head_id).
    """
    query = """
        SELECT fir_internal_id as id, crime_no, registered_date as date,
               crime_head_id, crime_sub_head_id
        FROM cases
        WHERE crime_sub_head_id = ?
        LIMIT ?
    """
    return await ztsql_query(query, [crime_sub_head_id, limit])

async def get_crime_sub_head_stats(crime_sub_head_id: str = None) -> list:
    """Aggregate case counts, optionally filtered by a resolved crime sub-head."""
    query = "SELECT crime_sub_head_id, COUNT(fir_internal_id) as total_cases FROM cases"
    params = []
    if crime_sub_head_id:
        query += " WHERE crime_sub_head_id = ?"
        params.append(crime_sub_head_id)
    query += " GROUP BY crime_sub_head_id"
    return await ztsql_query(query, params)
